name: Deploy to Windows EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
      - name: Pull latest code
        run: git pull origin main
      - name: Restart kiwoom api service
        run: nssm restart stock-auto-trading-kiwoom
