name: Deploy to Windows EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v3
      # - name: Pull latest code
      #   run: git pull origin main
      # - name: Restart FastAPI service
      #   run: nssm restart fastapi-service
